### ISSUE TITLE
Reading Mode Issue

### ISSUE THREAD

**Issue by JShiesty-dev** [Snd-R/kurp#1]
When using kurp and the reading mode is set to "Webtoon", the page jumps to that image every time an image is upscaled. This makes it impossible for readers using this reading mode to read due to the page scrolling around from image to image. Not sure if this can be prevented, if not, would it be possible to disable upscaling for this specific reading mode? To reproduce this issue, turn on webtoon reading mode and load up a book while kurp is running. Wait a few seconds or so for other pages to be upscaled, you will then see the page jumps from image to image.

**Comment by Snd-R** [comment]
Works fine for me on both chrome and firefox
The only difference there could be is the speed at which images are loaded. Their display is handled by reader in ui

**Comment by JShiesty-dev** [comment]
Could you try it on your phone? It works on my PC (Chrome) but not on my iPhone (Safari).

**Comment by JShiesty-dev** [comment]
Ok wow. I just tried it on Safari and it works fine. Turns out this might be a PWA-specific issue. Only PWA has this issue I guess. Interesting...

**Comment by JShiesty-dev** [comment]
Never mind I just tried on PWA again and everything is fine. So strange... I will close this issue since it must have been a one-off thing or something weird on my end.
