### ISSUE TITLE
how to set up models

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [Snd-R/kurp#4]
I was hoping to try this project, but it seems I missed a step in the setup. I created a `docker-compose.yml` file, ran `docker compose up` and in the logs I see:
```
kurp  |  fopen /config/models/models-cunet/scale2.0x_model.param failed
kurp  |  fopen /config/models/models-cunet/scale2.0x_model.bin failed
```
I figured I need to download the models myself. Where should I download these models (waifu2x and realcugan) from? I tried cloning these repos:
 - [waifu2x](https://github.com/nagadomi/waifu2x/)
 - [realcugan-ncnn-vulkan](https://github.com/nihui/realcugan-ncnn-vulkan)

and changing `models_path` for `waifu2x` and `realcugan` entries in `config.yml` to the `models` directory in the corresponding repos.

I am not sure if this is the right way as for waifu2x kurp tries to open `models/models-cunet/scale2.0x_model.param` and there is no `models-cunet` directory in the repo (there's only a `cunet` directory with incompatible files).

**Comment by Snd-R** [comment]
I'd advise to create a default config from readme. The problem seem to be wrong default model path when no value is set

For docker deployments it should be :
```
waifu2x:
  models_path: "./models"
```

or KURP_WAIFU2X.MODELS_PATH=./models environment variable

**Comment by papaj-na-wrotkach** [comment]
Weird, I thought I already had this set to `./models` when I tried to run kurp earlier and changed it to the location of the `models` dir in the waifu2x repo because it wasn't working. I changed it back and it's working now. It might have been a stupid mistake on my part (like forgetting to save the file). Thanks for help!
